import React from 'react';

const Template = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure aperiam minus, perferendis, distinctio sint architecto cupiditate a exercitationem, deleniti odit officiis? Voluptates, officia necessitatibus incidunt minus, ex cum sequi at molestiae minima quasi ipsum ipsa. Vel, tempore. Doloremque corrupti libero dolorum animi exercitationem explicabo earum recusandae. Modi ipsum minus fuga aspernatur voluptatum placeat quia illum officiis! Maxime architecto alias exercitationem, corrupti earum natus provident autem facilis officiis aut veritatis ex eligendi est accusantium sequi veniam. Labore perferendis, maxime ad quia quasi quos expedita tempore inventore libero ullam voluptates asperiores quis minus harum fugit consectetur. Obcaecati aspernatur quia suscipit mollitia voluptas harum eveniet odio qui ut, provident culpa et distinctio voluptates molestiae tempora voluptatum reprehenderit ullam perferendis nihil ipsum ratione placeat officiis! Optio magnam error, beatae hic voluptatem consectetur ab totam quo accusantium quibusdam possimus esse eos velit repellat! Dicta odit consectetur deleniti fugit tempora pariatur nemo quas facilis suscipit accusantium alias repellendus placeat asperiores ipsum dolorem ipsam libero eligendi enim ad ea, delectus optio natus quo! Incidunt delectus eligendi asperiores quo mollitia sunt ipsum, doloremque sequi illum dolor. Ipsum laborum ab velit dignissimos quo veniam saepe impedit ratione, doloremque recusandae error? Odit error ex, dignissimos ipsa ab ad placeat aperiam mollitia necessitatibus facere veniam assumenda. Culpa numquam enim facere. Iure quidem quas praesentium iusto, accusamus dolor magnam iste provident vero deleniti, ex consequuntur nulla fugit? Quos placeat quod veniam, debitis sunt beatae eaque id unde officiis, deleniti sit et, iste odio blanditiis iusto recusandae molestias consequuntur amet ex natus eligendi deserunt quis. Libero quis veniam nulla quibusdam eaque harum voluptatum nemo et, laboriosam sapiente rem consequuntur quam asperiores aspernatur doloribus excepturi quaerat itaque architecto animi commodi. Aperiam, vero voluptate, quasi rerum nam error ex tenetur minus excepturi adipisci iste cum quae temporibus quibusdam necessitatibus sapiente deserunt iusto ab perferendis placeat?</p>
        </div>
    );
};

export default Template;